version: 2

sources:
  - name: staging
    database: "{{ env_var('DBT_DATABASE', 'playground-martin') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'stackoverflow') }}"
      # loaded_at_field: record_loaded_at
    tables:
      - name: stackoverflow_survey_2020
      - name: stackoverflow_survey_2021
      - name: stackoverflow_survey_2022
      - name: stackoverflow_survey_2023
      - name: stackoverflow_survey_2024

models:
    - name: stg_stackoverflow_meta
      description: "Aggregated meta-informations for the surveys"

    - name: stg_stackoverflow_data
      description: "Unioned data for the surveys with chosen attributes"
