id: 03_stackoverlow_ingestion_scheduled
namespace: stackoverflow

description: |
  Uploading local zip files, extract them, upload csv-files to GCS and create external and not-external table using scheduled triggers.

variables:
  local_file_name: "stack-overflow-developer-survey-{{trigger.date | date('yyyy')}}.zip"
  local_file_path: "/tmp/kestra-wd/stackoverflow/{{vars.local_file_name}}"
  tmp_file_name: "stackoverflow_survey_{{trigger.date | date('yyyy')}}.csv"
  table_name: "stackoverflow_survey_{{trigger.date | date('yyyy')}}"
  gcs_file: "gs://playground-martin-stackoverflow-survey-data-bucket/{{vars.tmp_file_name}}"

tasks:
  - id: set_label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      file: "{{render(vars.local_file_name)}}"

  - id: unzip_and_upload_to_internal_storage
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      # Clear the directory if it exists
      - rm -rf /tmp/kestra-wd/unzipped
      # Create the directory again
      - mkdir -p /tmp/kestra-wd/unzipped
      # unzipping
      - unzip {{render(vars.local_file_path)}} -d /tmp/kestra-wd/unzipped
      # renaming
      - mv -f /tmp/kestra-wd/unzipped/survey_results_public.csv /tmp/kestra-wd/unzipped/{{render(vars.tmp_file_name)}}
      # writing in internal storage so that gcs.upload can use it
      - cat /tmp/kestra-wd/unzipped/{{render(vars.tmp_file_name)}} > {{render(vars.tmp_file_name)}}
    outputFiles:
      - "{{render(vars.tmp_file_name)}}"

  - id: upload_to_gcs
    type: io.kestra.plugin.gcp.gcs.Upload
    from: "{{ outputs.unzip_and_upload_to_internal_storage.outputFiles[render(vars.tmp_file_name)] }}"
    to: "{{render(vars.gcs_file)}}"
    
  - id: create_external_table
    type: io.kestra.plugin.gcp.bigquery.Query
    sql: |
      CREATE OR REPLACE EXTERNAL TABLE `{{kv('GCP_PROJECT_ID')}}.{{kv('GCP_DATASET')}}.{{render(vars.table_name)}}_ext`
      OPTIONS (
          format = 'CSV',
          uris = ['{{render(vars.gcs_file)}}'],
          skip_leading_rows = 1, -- to skip the header row
          allow_quoted_newlines = true,
          null_marker = 'NA'  -- Treats "NA" as NULL
      );

  - id: create_standard_table
    type: io.kestra.plugin.gcp.bigquery.Query
    sql: |
      CREATE OR REPLACE TABLE `{{kv('GCP_PROJECT_ID')}}.{{kv('GCP_DATASET')}}.{{render(vars.table_name)}}` AS
      SELECT *
      FROM `{{kv('GCP_PROJECT_ID')}}.{{kv('GCP_DATASET')}}.{{render(vars.table_name)}}_ext`

pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{kv('GCP_CREDS')}}"
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_NAME')}}"

# scheduled on the first of every year
triggers:
  - id: stackoverflow_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "1 0 1 1 *"
