version: 2

models:
    - name: stackoverflow_meta
      description: "Aggregated meta-informations for the surveys"

    - name: stackoverflow_data_participants
      description: "Participant-related data"

    - name: stackoverflow_data_unnested
      description: "Unnested data for database-related columns joined with participant-data"

    - name: stackoverflow_data_clustered
      description: "Clustered table for the final visualisation"
